# Because this library needs to be built,
# we can't easily point package.json files at the git repo for easy cross-repo testing.
#
# This workflow brings back that capability by placing the compiled assets on a "dist" branch
# (configurable via the "branch" option below)
name: Push dist

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          # uses Volta!
          node-version-file: 'package.json'
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - uses: kategengler/put-built-npm-package-contents-on-branch@v2.0.0
        with:
          branch: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'ember-cli-stripe'
